/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chessrankingproject;

import java.awt.Color;

/**
 *
 * @author Travis Lowe
 */
public class dialogForm extends javax.swing.JPanel {

    /**
     * Creates new form dialogForm
     */
    
    private Player newP1 = new Player();
    private Player newP2 = new Player();
    
    private Player Oldp1 = new Player();
    private Player Oldp2 = new Player();
    
    public dialogForm() {
        initComponents();
    }
    
    public dialogForm(Player p1, Player p2) {
        initComponents();
        
        this.newP1 = p1;
        this.newP2 = p2;
        
        
    }

    dialogForm(PlayerArrayList OldPlayerList, Player SelectedPlayer, Player SelectedOppnt, int wins, int losses, int draws) {
        initComponents();
        this.newP1 = SelectedPlayer;
        this.newP2 = SelectedOppnt;
        
        for(Player p: OldPlayerList){
        
            if(p.getId() == newP1.getId()){ // if id of modified player is found in the list. . .
            
              this.Oldp1 = p.getCopy();
              
            };
            
            if(p.getId() == newP2.getId()){
            
                this.Oldp2 = p.getCopy();
            }
        
        }
        
        calcAndDisplayPlayerInfo(wins,losses,draws);
        
        
    }

    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        Player1NameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p1OldwinsTextfield = new javax.swing.JTextField();
        p1IdTextfield = new javax.swing.JTextField();
        p1OldlossesTextField = new javax.swing.JTextField();
        p1OldDrawsTextField = new javax.swing.JTextField();
        p1OldGamesPlayedTextField = new javax.swing.JTextField();
        p1DeltaWinsTextField = new javax.swing.JTextField();
        p1deltalossTextField = new javax.swing.JTextField();
        p1DeltaDrawsTextField = new javax.swing.JTextField();
        p1deltaGamesPlayedTextfield = new javax.swing.JTextField();
        p1OldRatingTextBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        p1deltaRatingTextfield1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        p2DeltaRatingTextfield = new javax.swing.JTextField();
        p2DeltaWinsTextField = new javax.swing.JTextField();
        Player2NameTextField = new javax.swing.JTextField();
        p2deltalossTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        p2DeltaDrawsTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        p2deltaGamesPlayedTextfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        p2OldwinsTextfield = new javax.swing.JTextField();
        p2IdTextfield = new javax.swing.JTextField();
        p2OldlossesTextField = new javax.swing.JTextField();
        p2OldRatingTextBox = new javax.swing.JTextField();
        p2OldDrawsTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        p2OldGamesPlayedTextField = new javax.swing.JTextField();

        Player1NameTextField.setBackground(new java.awt.Color(240, 240, 240));
        Player1NameTextField.setText("Player 1");
        Player1NameTextField.setBorder(null);

        jLabel2.setText("ID:");

        jLabel3.setText("Wins:");

        jLabel4.setText("Losses:");

        jLabel5.setText("Draws:");

        jLabel6.setText("Games Played:");

        p1OldwinsTextfield.setBackground(new java.awt.Color(228, 225, 225));
        p1OldwinsTextfield.setText("       ");

        p1IdTextfield.setBackground(new java.awt.Color(228, 225, 225));
        p1IdTextfield.setText("       ");

        p1OldlossesTextField.setBackground(new java.awt.Color(228, 225, 225));
        p1OldlossesTextField.setText("       ");

        p1OldDrawsTextField.setBackground(new java.awt.Color(228, 225, 225));
        p1OldDrawsTextField.setText("       ");

        p1OldGamesPlayedTextField.setBackground(new java.awt.Color(228, 225, 225));
        p1OldGamesPlayedTextField.setText("        ");

        p1DeltaWinsTextField.setBackground(new java.awt.Color(240, 240, 240));
        p1DeltaWinsTextField.setText("    ");
        p1DeltaWinsTextField.setBorder(null);
        p1DeltaWinsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1DeltaWinsTextFieldActionPerformed(evt);
            }
        });

        p1deltalossTextField.setBackground(new java.awt.Color(240, 240, 240));
        p1deltalossTextField.setBorder(null);

        p1DeltaDrawsTextField.setBackground(new java.awt.Color(240, 240, 240));
        p1DeltaDrawsTextField.setBorder(null);

        p1deltaGamesPlayedTextfield.setBackground(new java.awt.Color(240, 240, 240));
        p1deltaGamesPlayedTextfield.setBorder(null);

        p1OldRatingTextBox.setBackground(new java.awt.Color(228, 225, 225));
        p1OldRatingTextBox.setText("        ");

        jLabel9.setText("Rating:");

        p1deltaRatingTextfield1.setBackground(new java.awt.Color(240, 240, 240));
        p1deltaRatingTextfield1.setBorder(null);

        jLabel1.setText("Are These Results Acceptable??");

        p2DeltaRatingTextfield.setBackground(new java.awt.Color(240, 240, 240));
        p2DeltaRatingTextfield.setBorder(null);

        p2DeltaWinsTextField.setBackground(new java.awt.Color(240, 240, 240));
        p2DeltaWinsTextField.setText("    ");
        p2DeltaWinsTextField.setBorder(null);
        p2DeltaWinsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2DeltaWinsTextFieldActionPerformed(evt);
            }
        });

        Player2NameTextField.setBackground(new java.awt.Color(240, 240, 240));
        Player2NameTextField.setText("Player 2");
        Player2NameTextField.setBorder(null);

        p2deltalossTextField.setBackground(new java.awt.Color(240, 240, 240));
        p2deltalossTextField.setBorder(null);

        jLabel7.setText("ID:");

        p2DeltaDrawsTextField.setBackground(new java.awt.Color(240, 240, 240));
        p2DeltaDrawsTextField.setBorder(null);

        jLabel8.setText("Wins:");

        p2deltaGamesPlayedTextfield.setBackground(new java.awt.Color(240, 240, 240));
        p2deltaGamesPlayedTextfield.setBorder(null);

        jLabel10.setText("Losses:");

        jLabel11.setText("Draws:");

        jLabel12.setText("Games Played:");

        p2OldwinsTextfield.setBackground(new java.awt.Color(228, 225, 225));
        p2OldwinsTextfield.setText("       ");

        p2IdTextfield.setBackground(new java.awt.Color(228, 225, 225));
        p2IdTextfield.setText("       ");

        p2OldlossesTextField.setBackground(new java.awt.Color(228, 225, 225));
        p2OldlossesTextField.setText("       ");

        p2OldRatingTextBox.setBackground(new java.awt.Color(228, 225, 225));
        p2OldRatingTextBox.setText("        ");

        p2OldDrawsTextField.setBackground(new java.awt.Color(228, 225, 225));
        p2OldDrawsTextField.setText("       ");

        jLabel13.setText("Rating:");

        p2OldGamesPlayedTextField.setBackground(new java.awt.Color(228, 225, 225));
        p2OldGamesPlayedTextField.setText("        ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p1OldRatingTextBox)
                            .addComponent(p1IdTextfield)
                            .addComponent(p1OldwinsTextfield)
                            .addComponent(p1OldlossesTextField)
                            .addComponent(p1OldDrawsTextField)
                            .addComponent(p1OldGamesPlayedTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(p1deltalossTextField)
                                .addComponent(p1DeltaDrawsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addComponent(p1deltaGamesPlayedTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addComponent(p1DeltaWinsTextField))
                            .addComponent(p1deltaRatingTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(Player1NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p2IdTextfield)
                            .addComponent(p2OldwinsTextfield)
                            .addComponent(p2OldlossesTextField)
                            .addComponent(p2OldDrawsTextField)
                            .addComponent(p2OldGamesPlayedTextField)
                            .addComponent(p2OldRatingTextBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(p2deltalossTextField)
                                .addComponent(p2DeltaDrawsTextField)
                                .addComponent(p2deltaGamesPlayedTextfield)
                                .addComponent(p2DeltaWinsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p2DeltaRatingTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Player2NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Player1NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(p1IdTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(p1DeltaWinsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(p1OldwinsTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(p1OldlossesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p1deltalossTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(p1OldDrawsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(p1DeltaDrawsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1deltaGamesPlayedTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p1OldGamesPlayedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p1OldRatingTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(p1deltaRatingTextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Player2NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(p2IdTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(p2DeltaWinsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(p2OldwinsTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(p2OldlossesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p2deltalossTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(p2OldDrawsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(p2DeltaDrawsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2deltaGamesPlayedTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p2OldGamesPlayedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(p2OldRatingTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(p2DeltaRatingTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void p1DeltaWinsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1DeltaWinsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1DeltaWinsTextFieldActionPerformed

    private void p2DeltaWinsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2DeltaWinsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p2DeltaWinsTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Player1NameTextField;
    private javax.swing.JTextField Player2NameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField p1DeltaDrawsTextField;
    private javax.swing.JTextField p1DeltaWinsTextField;
    private javax.swing.JTextField p1IdTextfield;
    private javax.swing.JTextField p1OldDrawsTextField;
    private javax.swing.JTextField p1OldGamesPlayedTextField;
    private javax.swing.JTextField p1OldRatingTextBox;
    private javax.swing.JTextField p1OldlossesTextField;
    private javax.swing.JTextField p1OldwinsTextfield;
    private javax.swing.JTextField p1deltaGamesPlayedTextfield;
    private javax.swing.JTextField p1deltaRatingTextfield1;
    private javax.swing.JTextField p1deltalossTextField;
    private javax.swing.JTextField p2DeltaDrawsTextField;
    private javax.swing.JTextField p2DeltaRatingTextfield;
    private javax.swing.JTextField p2DeltaWinsTextField;
    private javax.swing.JTextField p2IdTextfield;
    private javax.swing.JTextField p2OldDrawsTextField;
    private javax.swing.JTextField p2OldGamesPlayedTextField;
    private javax.swing.JTextField p2OldRatingTextBox;
    private javax.swing.JTextField p2OldlossesTextField;
    private javax.swing.JTextField p2OldwinsTextfield;
    private javax.swing.JTextField p2deltaGamesPlayedTextfield;
    private javax.swing.JTextField p2deltalossTextField;
    // End of variables declaration//GEN-END:variables

    private void calcAndDisplayPlayerInfo(int wins, int losses, int draws) {
        
        // Set names
        Player1NameTextField.setEditable(false);
        Player2NameTextField.setEditable(false);
        Player1NameTextField.setText( newP1.getFirstName()+ " " + newP1.getLastName() + ":");
        Player2NameTextField.setText( newP2.getFirstName()+ " " + newP2.getLastName() + ":");
        
        // Set IDs
        p1IdTextfield.setEditable(false);
        p2IdTextfield.setEditable(false);
        p1IdTextfield.setText(Integer.toString(newP1.getId()));
        p2IdTextfield.setText(Integer.toString(newP2.getId()));
        
        // Set wins
        p1OldwinsTextfield.setEditable(false);
        p1DeltaWinsTextField.setEditable(false);
        p2OldwinsTextfield.setEditable(false);
        p2DeltaWinsTextField.setEditable(false);
        p2deltalossTextField.setEditable(false);
        
        p1OldwinsTextfield.setText(Integer.toString(Oldp1.getGamesWon()));
        p2OldwinsTextfield.setText(Integer.toString(Oldp2.getGamesWon()));
        p1DeltaWinsTextField.setForeground(Color.GREEN);
        p2DeltaWinsTextField.setForeground(Color.GREEN);
        p2deltalossTextField.setForeground(Color.red);
        if(wins > 0){
            
            p1DeltaWinsTextField.setText("+ " + Integer.toString(wins ) );
            p2deltalossTextField.setText("+ " + Integer.toString(wins));
        }
        
        // set losses
        p1OldlossesTextField.setEditable(false);
        p2OldlossesTextField.setEditable(false);
        p1deltalossTextField.setEditable(false);
        
        p1OldlossesTextField.setText(Integer.toString(Oldp1.getGamesLost()));
        p2OldlossesTextField.setText(Integer.toString(Oldp2.getGamesLost()));
        p1deltalossTextField.setForeground(Color.red);
        if(losses > 0){
        
            p1deltalossTextField.setText("+ " + Integer.toString(losses ) );
            p2DeltaWinsTextField.setText("+ " + Integer.toString(losses ) );
        }
        
        
        // set draws
        p1OldDrawsTextField.setEditable(false);
        p1DeltaDrawsTextField.setEditable(false);
        p2OldDrawsTextField.setEditable(false);
        p2DeltaDrawsTextField.setEditable(false);
        
        p1OldDrawsTextField.setText(Integer.toString(Oldp1.getGamesDrawn()));
        p2OldDrawsTextField.setText(Integer.toString(Oldp2.getGamesDrawn()));
        if(draws > 0 ){
        
            p1DeltaDrawsTextField.setText("+ " + Integer.toString(draws));
            p2DeltaDrawsTextField.setText("+ " + Integer.toString(draws));
        }
        
        // Set Games Played
        p1OldGamesPlayedTextField.setEditable(false);
        p1deltaGamesPlayedTextfield.setEditable(false);
        p2OldGamesPlayedTextField.setEditable(false);
        p2deltaGamesPlayedTextfield.setEditable(false);
        
        p1OldGamesPlayedTextField.setText(Integer.toString(Oldp1.getGamesPlayed()));
        p2OldGamesPlayedTextField.setText(Integer.toString(Oldp2.getGamesPlayed()));
        
        p1deltaGamesPlayedTextfield.setText("+ " + Integer.toString(wins + losses + draws));
        p2deltaGamesPlayedTextfield.setText("+ " + Integer.toString(wins + losses + draws));
        
        
        //Set Scores
        p1OldRatingTextBox.setEditable(false);
        p2OldRatingTextBox.setEditable(false);
        p1OldRatingTextBox.setText(Float.toString(Oldp1.getCurrentRating()));
        p2OldRatingTextBox.setText(Float.toString(Oldp2.getCurrentRating()));
    }
}
