/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.chessrankingproject;
import java.awt.Color;
import java.awt.List;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author lando
 */
public class PlayerFrame extends javax.swing.JFrame {

    private PlayerArrayList PlayerList = new PlayerArrayList();
    private ArrayList<PlayerEventListener> listenerList = new ArrayList<>();
    DefaultListModel<Player> PlayerListModel = new DefaultListModel<>();
    Player selectedRemovePlayer;
    
    /**
     * Creates new form PlayerFrame
     */
    public PlayerFrame() {
        initComponents();
        
        RemovePlayerList.setModel(PlayerListModel);
        
        RemovePlayerButton.setEnabled(false);
        
        ErrorTextArea.setForeground(Color.red);
    }
    
    private static int x = 0;
    
    public static int buttonaction()
    {
            return x;
    }
    public PlayerFrame(PlayerArrayList Plist){
    
        initComponents();
        PlayerList = Plist;
        
          for (Player p : PlayerList){
            
            PlayerListModel.addElement(p);
        }
        RemovePlayerList.setModel(PlayerListModel);
        
        RemovePlayerButton.setEnabled(false);
        
        ErrorTextArea.setForeground(Color.red);
        
        
        
        
    }
    
    public synchronized void addListener (PlayerEventListener listener){ // add functions that will listen for the changes on this frame
        
        listenerList.add(listener);
    
    }
    
    private synchronized void fireEvent(java.util.EventObject evt){
        
        if (evt instanceof UpdateDatabaseEvent){ 
    
                if( !( PlayerList == null || PlayerList.isEmpty() )  ){    
                    for(PlayerEventListener eachplistener : listenerList){

                    eachplistener.updateDatabase(PlayerList);
                    }
                }
        }
        else if(evt instanceof PlayerTextEvent){
          
                for(PlayerEventListener eachplistener : listenerList){

                    eachplistener.updateDebugText(((PlayerTextEvent) evt).getText());
                    }
        
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        RemovePlayerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RemovePlayerList = new javax.swing.JList<>();
        RemoveListLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RatingTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        FirstNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AddPlayerButton = new javax.swing.JButton();
        AcceptButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ErrorTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Player Frame");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton(evt);
            }
        });

        RemovePlayerButton.setText("Remove Player");
        RemovePlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovePlayerButtonActionPerformed(evt);
            }
        });

        RemovePlayerList.setModel(PlayerListModel);
        RemovePlayerList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                RemovePlayerListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(RemovePlayerList);

        RemoveListLabel.setText("Players in DataBase");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        RatingTextField.setText("Enter Elo Rating");
        RatingTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RatingTextFieldMouseClicked(evt);
            }
        });

        jLabel4.setText("I.D.");

        jLabel1.setText("First Name");

        IDTextField.setText("Enter Player I.D.");
        IDTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDTextFieldMouseClicked(evt);
            }
        });

        FirstNameTextField.setText("Enter First Name");
        FirstNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirstNameTextFieldMouseClicked(evt);
            }
        });

        jLabel2.setText("Last Name");

        LastNameTextField.setText("Enter Last Name");
        LastNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LastNameTextFieldMouseClicked(evt);
            }
        });

        jLabel3.setText("ELO Rating");

        AddPlayerButton.setText("Add Player");
        AddPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlayerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(AddPlayerButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(FirstNameTextField)
                                .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RatingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(AddPlayerButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(RatingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        AcceptButton.setText("Accept and Close");
        AcceptButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceptButtonMouseClicked(evt);
            }
        });

        jScrollPane2.setBorder(null);

        ErrorTextArea.setEditable(false);
        ErrorTextArea.setBackground(new java.awt.Color(240, 240, 240));
        ErrorTextArea.setColumns(20);
        ErrorTextArea.setRows(5);
        ErrorTextArea.setBorder(null);
        jScrollPane2.setViewportView(ErrorTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(RemovePlayerButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RemoveListLabel)
                                .addGap(61, 61, 61))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AcceptButton)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(RemoveListLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RemovePlayerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(AcceptButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    private void CancelButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton

        this.dispose();    
    }//GEN-LAST:event_CancelButton

    private void GamesPlayedTextBox(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamesPlayedTextBox
        // TODO add your handling code here:
    }//GEN-LAST:event_GamesPlayedTextBox

    private void GamesWonTextBox(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamesWonTextBox
        // TODO add your handling code here:
    }//GEN-LAST:event_GamesWonTextBox

    private void FirstNameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstNameTextFieldMouseClicked
        FirstNameTextField.setText("");
    }//GEN-LAST:event_FirstNameTextFieldMouseClicked

    private void LastNameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastNameTextFieldMouseClicked
        LastNameTextField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldMouseClicked

    
    private void RemovePlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovePlayerButtonActionPerformed
        PlayerList.remove(selectedRemovePlayer);
        for(int i = 0; i< PlayerListModel.getSize(); i++){
        
         if (PlayerListModel.get(i).getId() == selectedRemovePlayer.getId())
             PlayerListModel.remove(i);
        }
    }//GEN-LAST:event_RemovePlayerButtonActionPerformed

    private void RatingTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RatingTextFieldMouseClicked
        RatingTextField.setText("");
    }//GEN-LAST:event_RatingTextFieldMouseClicked

    private void AddPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlayerButtonActionPerformed
        
        boolean duplPlayer = false;
        boolean duplID = false;
        
        Player NPlayer = new Player();
        String firstname = "";
        String lastname = "";
        int id =0;
        float rating =0 ;
        
        try {
            firstname = FirstNameTextField.getText().trim();
            lastname = LastNameTextField.getText().trim();
            id = Integer.parseInt(IDTextField.getText().trim());
            rating = Float.parseFloat(RatingTextField.getText().trim());
            
            
            for(Player p : PlayerList){
            
            if(firstname.equalsIgnoreCase(p.getFirstName())){
                
                if(lastname.equalsIgnoreCase(p.getLastName())){
                
                    duplPlayer = true;
                }
                
            }
            
            if(id == p.getId()){
            
                duplID = true;
            }
            
                
            }
            
           if(duplPlayer == false && duplID == false){
       
                NPlayer.setFirstName(firstname);
                NPlayer.setLastName(lastname);
                NPlayer.setId(id);
                NPlayer.setCurrentRating(rating);
                NPlayer.setLowestRating(rating);
                NPlayer.setHighestRating(rating);

        
                PlayerList.add(NPlayer);
        
                PlayerListModel.addElement(NPlayer);
                
                ErrorTextArea.setForeground(Color.black);
                String valid = "Player " + NPlayer.getCombNameFL()+ " successfully added!";
                ErrorTextArea.setText(valid);
                
                FirstNameTextField.setText("");
                LastNameTextField.setText("");
                IDTextField.setText("");
                RatingTextField.setText("");
   
            }else{
           
                    if(duplPlayer == true){
                        ErrorTextArea.setForeground(Color.red);
                        ErrorTextArea.setText("A player already exists with that name.\nTry a different first or last name please.\n\n");

                    }

                    if(duplID == true){
                         ErrorTextArea.setForeground(Color.red);
                         ErrorTextArea.setText("A player already exists with that ID number.\nTry a different ID number please\n\n");
                         IDTextField.setText("");
                    }
           
           }      
                                
            
        }catch(NumberFormatException ne){
            ErrorTextArea.setForeground(Color.red);
            ErrorTextArea.append("Invalid numeric entry. Try those numbers again!!.\n");
            IDTextField.setText("");
            RatingTextField.setText("");
        }
        catch (Exception e) {
            ErrorTextArea.setForeground(Color.red);
            ErrorTextArea.append("Invalid entry. Try again.\n");
            FirstNameTextField.setText("");
            LastNameTextField.setText("");
            IDTextField.setText("");
            RatingTextField.setText("");
        }
        
        
// scan for first name match (string equals ignore case)
// if true scan for last name match
// if true prompt Player" player with that name already exists" 


// scan if
        
  
        
    }//GEN-LAST:event_AddPlayerButtonActionPerformed

    private void IDTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDTextFieldMouseClicked
        IDTextField.setText("");
    }//GEN-LAST:event_IDTextFieldMouseClicked

    private void AcceptButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptButtonMouseClicked
        
        
        int result = JOptionPane.showConfirmDialog(rootPane, "Are You sure about your options ??");
        if (result == JOptionPane.YES_OPTION){
            if(PlayerList.isEmpty()){
            PlayerList.emptyStatus =  1;
            PlayerList.add(new Player("Empty", "Player"));
            }
        
            fireEvent(new UpdateDatabaseEvent(PlayerList));
            fireEvent(new PlayerTextEvent(""));
            this.dispose();
        }
    }//GEN-LAST:event_AcceptButtonMouseClicked

    private void RemovePlayerListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_RemovePlayerListValueChanged
       RemovePlayerButton.setEnabled(true);
        selectedRemovePlayer = RemovePlayerList.getSelectedValue();
    }//GEN-LAST:event_RemovePlayerListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JButton AddPlayerButton;
    private javax.swing.JTextArea ErrorTextArea;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField RatingTextField;
    private javax.swing.JLabel RemoveListLabel;
    private javax.swing.JButton RemovePlayerButton;
    private javax.swing.JList<Player> RemovePlayerList;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
